# Generated by Django 4.2.4 on 2023-08-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Dept',
        ),
    ]
